test('Very first test', () => {
   throw new Error('Oh my mistake!');
});